apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dannsk94/VKcloud-LAB-4.git'
    path: kubernetes
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: web-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
